version: '2'
services:
    php:
        build: ./php
        restart: always
        volumes:
            - ./app:/var/www/app
            #- ./php/php.ini:/usr/local/etc/php/php.ini
        container_name: "AppSymfony"
    nginx:
        image: nginx:latest
        restart: always
        ports:
          - "6888:80"
        volumes:
            - ./app:/var/www/app
            - ./nginx/app.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
    mysql:
        image: mysql:8
        command: mysqld --sql_mode="" --default_authentication_plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: toor
        ports:
            - "7333:3306"
        container_name: "SQLSymfony1"
    adminer:
        image: adminer
        restart: always
        ports:
          - "6081:8080"
